# Generated by Django 3.2.5 on 2022-04-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0007_auto_20220429_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='customer',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='petshop.customer'),
        ),
    ]
