# Generated by Django 3.2.5 on 2022-04-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petshop', '0008_alter_pet_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='recommender_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
